### ISSUE TITLE
error response from deamon with docker-compose 

### ISSUE THREAD

**Issue by david-alber** [camunda/camunda-platform#100]
I want to locally run the camunda platform. 
Following the instructions (clone repo & run `docker-compose up -d` from inside the camunda-platform directory results in the error: 
`Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error setting rlimits for ready process: error setting rlimit type 8: operation not permitted: unknown`

The local web apps (localhost:8081,localhost:8082,localhost:8083,localhost:8084) are not reachable.
All containers seem to be created but not all are running:

`NAME                COMMAND                  SERVICE             STATUS              PORTS
connectors          "/start.sh"              connectors          created             
elasticsearch       "/bin/tini -- /usr/l…"   elasticsearch       created             0.0.0.0:9200->9200/tcp, 0.0.0.0:9300->9300/tcp, :::9200->9200/tcp, :::9300->9300/tcp
identity            "java -jar identity.…"   identity            running (healthy)   0.0.0.0:8084->8084/tcp, :::8084->8084/tcp
keycloak            "/opt/bitnami/script…"   keycloak            running (healthy)   0.0.0.0:18080->8080/tcp, :::18080->8080/tcp
operate             "/bin/tini -- /usr/l…"   operate             created             
optimize            "/sbin/tini -- ./opt…"   optimize            created             
postgres            "docker-entrypoint.s…"   postgres            running (healthy)   5432/tcp
tasklist            "java -XX:+ExitOnOut…"   tasklist            created             
zeebe               "tini -- /usr/local/…"   zeebe               created`

How can this be resolved?

**Comment by jessesimpson36** [comment]
Hi @david-alber ,

I do not believe this issue is related to the camunda-platform code or docker-compose configuration. It looks to me like this is a problem with your docker installation, or perhaps some detail related to your environment.

Some information about the error message you're getting.

> error setting rlimits for ready process ... rlimit type 8: operation not permitted
I believe this is related to the following lines: https://github.com/camunda/camunda-platform/blob/main/docker-compose.yaml#L275-L278

Your docker daemon probably does not have the permissions necessary to set rlimits.


For me to help you further, I'm going to need to know some information about your system:
Please provide the output from this command
```
docker info
```
And also if you've configured your docker daemons  daemon.json in any way.
```
cat /etc/docker/daemon.json
```

And I'd like to know what operating system you're running on.  Is this Ubuntu Linux? RHEL? Windows 10? Mac OS ?

**Comment by david-alber** [comment]
@jessesimpson36 Thanks for your reply. You are right the issue was related to docker-compose. Switching to podman/podman-compose resolved the issue for me.
