### ISSUE TITLE
Reduce different ways of deploying our application

### ISSUE THREAD

**Issue by jessesimpson36** [camunda/camunda-platform#168]
Currently, we have 3 ways of deploying the docker compose version of camunda platform.
1. Deploy docker-compose-core.yaml
2. Deploy docker-compose.yaml
3. Deploy docker-compose.yaml with docker-compose-web-modeler.yaml

This introduces unnecessary complexity, because:

1. 3 methods of deploying our compose files introduces more of a risk that one of them will be dysfunctional.
2. We risk that changes to one compose file may not get properly added to the other compose files.  
3. We also need 3 versions of our CI checks to test that the 3 compose files will come up healthy. So 3 deployment methods of our CI pipelines need to be maintained in addition to the CI pipelines for each stable release in our stable/8.x branches.
4. Support / github issues sometimes gets into frustrations of users using one compose file vs the other.

But why do we have 3 different compose files? Do we need them?

I might be wrong, but as far as I can tell, the reason we might have  these files is to reduce system overhead and reduce startup time of the application for development purposes. Maybe you just don't want one or more services.

Here's why I think that's not an issue:
1. It takes only a minute to pull all images and start up all components using docker compose.  And further updates for development purposes take less time since you only need to run `docker compose up -d`  again, and only services with configuration changes will get updated.
2. There's not much of a reason to want to login via keycloak vs login via operate directly. It's the same username/password.
3. Not much system resources are being used. From my testing, about 4GB of RAM total for all components and a negligible amount of CPU usage.
4. If you don't want the modeler or Optimize, simply don't use it. Or don't expose the port.  Or remove those sections from YOUR docker compose file when you deploy.

Proposed actions:
- Remove docker-compose-core.yaml
- Combine docker-compose.yaml and docker-compose-web-modeler.yaml

Let me know if you disagree.

**Comment by felix-mueller** [comment]
Thanks for the proposal. 
From a developer point of view I would like to start only as little containers as possible to develop locally with camunda 8. That's why we have the core compose file. I dont want to have necessarily Web Modeler, Optimize, Keycloak only for local development.

I believe the Web Modeler and docker-compose.yaml can be merged.

One idea: Could we merge all and disable certain containers by using the profile functionality in docker-compose: 
https://docs.docker.com/compose/profiles/ 
Perhaps we can end up with one docker-compose but have a profile "core" which starts only the really needed containers?

**Comment by jessesimpson36** [comment]
I'm going to close this issue. I don't plan on doing anything about this right now. Maybe in the future we can reconsider, but the comments I've seen and what we've spoken about in meetings is that we still want 3 ways to deploy the docker compose deployment.
