### ISSUE TITLE
After upgrading my WebModeler installation all my data was gone

### ISSUE THREAD

**Issue by JensBrauckhoff** [camunda/camunda-platform#386]
I upgraded my WebModeler installation based on this Docker-Compose configuration from 8.3.0 to 8.3.2 and all my data was gone. I assume that the reason was that the PostgreSQL DB container did not have a volume for the DB files. I added a volume with a local change, yet I'm not sure if a WebModeller DB can cope with that during an upgrade. If WebModeller support upgrading the DB model automatically, I might contribute my change to this project if the team is interrested.

**Comment by aabouzaid** [comment]
@JensBrauckhoff It depends on the upgrade method.
Since Docker Compose is not designed for production workload, then the user should take care of the upgrade.

But generally speaking, an upgrade from 8.3.0 to 8.3.2 shouldn't have breaking changes and should use the same database and files (there was [a bug in v8.3.0](https://docs.camunda.io/docs/self-managed/operational-guides/update-guide/820-to-830/) which could be related)
