### ISSUE TITLE
Fix Health Check for Elastic Search

### ISSUE THREAD

**Issue by Chris-Maechler** [camunda/camunda-platform#471]
On local machines which don't have that many resources (and the docker compose files are supposed to be for local development) the health check will never become "green", it will only become "yellow" (but works completely fine).

So this test

"curl -f http://localhost:9200/_cat/health | grep -q green"

Should use something like egrep 'green|yellow' to cover that.

**Comment by mrgohin** [comment]
The provided compose file is building a single node elastic instance but keeps the default shard and replica setting.

Which is causing the "yellow" state because a third of the shards is not being assigned / replicated:

![image](https://github.com/camunda/camunda-platform/assets/38684218/f179f8c3-4cbe-423b-a73f-c5fd2b37dc40)

The work of making it possible to inject the needed JSON body for changing the mentioned settings is not in contrast with simply changing the health check to yellow.

**Comment by aabouzaid** [comment]
@Chris-Maechler Thanks for the suggestion, do you like to create a PR for it?
