### ISSUE TITLE
Tasklist: cannot access tasklist via docker-compose-core.yaml 

### ISSUE THREAD

**Issue by anyidea** [camunda/camunda-platform#97]
![CleanShot 2023-03-10 at 10 15 06@2x](https://user-images.githubusercontent.com/48710760/224206280-7fc57f6d-4139-4f55-95f5-3a22fb026dc1.png)
when i use `docker-compose-core.yaml` to start development environment, it seems to be redirected to `https`

**Comment by anyidea** [comment]
8.1.9 solve some problems when using docker-compose file to start up, but still left a new issue.
when i access `identify` from a remote host using IP adress, it will br redirected to `localhost`, other service solve this by setting url in compose file.

![CleanShot 2023-03-15 at 17 55 52](https://user-images.githubusercontent.com/48710760/225274833-4689a599-00fe-41bb-83b7-cbca4c6d9d61.gif)

**Comment by jessesimpson36** [comment]
https://github.com/camunda/camunda-platform/pull/126

This PR is merged, and should resolve your issue. Thanks for the contribution @anyidea .

As for the first part of your issue, I'm not sure what would cause the https redirection.  I don't think the docker-compose-core.yaml file was designed to be ran on a server instead of your local machine.

Re-open the issue with another comment if there's more to discuss on this. Personally, I'm not sure what the purpose of docker-compose-core.yaml is.   I would suggest using docker-compose.yaml instead.
